name: Build Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [pubsub, dynamic, static]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip Cheetah3

      - name: Build project
        run: python build.py -p ${{ matrix.project }}
